import { ReactNode } from "react"
import Header from "./Header"
import Head from "next/head"

const Layout = ({ children }: { children: ReactNode }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                {/* <script src="https://kit.fontawesome.com/ab72316f14.js" crossOrigin="anonymous"></script> */}
            </Head>
            <Header />
            <main className="main-content">{children}</main>
        </>)
}

export default Layout