services:
    backend:
        build: ./backend
        ports: 
            - 4000:4000
    #     command: npm run start
        volumes: 
            - ./backend/src/:/app/src/
            # Le volume permet d'avoir les modifications en direct sans la nécessité d'arrêter et de redémarrer le serveur. 

    frontend:
        build: ./frontend
        ports:
            - 3000:3000
    #     command: npm run dev
        volumes: 
            - ./frontend/src/:/app/src/

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: valuePassword