services:
    server:
        build: ./backend
        ports: 
            - 4000:4000
    #     command: npm run start
        volumes: 
            - ./backend/src/:/app/src/
            # Le volume permet d'avoir les modifications en direct sans la nécessité d'arrêter et de redémarrer le serveur. 
    # client:
    #     build: ./frontend
    #     ports:
    #         - 3000:3000
    #     command: npm run dev
    #     volumes: 
    #         - ./frontend/src/:/app/src/
    #         # - ./client/public/:/app/public
    #     # environment: 
    #     #     - WDS_SOCKET_PORT=8000
    # mongodb:
    #     image: mongo
    #     volumes: 
    #         - ./data:/data/db